[project]
name = "cafe-recomendation"
version = "0.1.0"
description = "카페 추천 시스템 서비스"
readme = "README.md"
requires-python = ">=3.11"
authors = [
    {name = "east-right", email = "wkfl1125@naver.com"}
]
dependencies = [
    "python-dotenv>=1.2.2",
    "openai>=2.38.0",
    "opensearch-py>=3.2.0",
    "sentence-transformers>=5.5.1",
    "langgraph>=0.2.0",
    "transformers>=4.40.0",
    "accelerate>=0.20.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
]

[tool.uv]
package = false
